name: pruebas
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^0.1.2
  flutter_webview_plugin: ^0.3.11
  http: ^0.12.0+4
  html: ^0.14.0+3
  provider: ^4.0.5
  video_player: ^0.10.12+2
  cloud_firestore: ^0.14.0+2
  flutter_radio_player: ^1.0.4
  firebase_auth: ^0.18.0+1
  firebase_core: ^0.5.0
  flutter_facebook_auth: ^0.2.4
  google_sign_in: ^4.5.3
  cached_network_image: ^2.2.0+1
  flutter_custom_clippers: ^1.1.1
  animate_do: ^1.7.2
  flutter_youtube: ^2.0.0
  url_launcher: ^5.5.2
  shared_preferences: ^0.5.8
  font_awesome_flutter: ^8.8.1
  bubble_bottom_bar: ^1.2.0
  sembast: ^2.4.7+4
  path: ^1.7.0
  path_provider: ^1.6.11
  

dev_dependencies:
  flutter_test:
    sdk: flutter
    
  flutter_launcher_icons: "^0.7.5"

flutter_icons:
  
  android: true 
  ios: true

flutter:


  uses-material-design: true


  assets:
    - assets/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-ExtraBold.ttf
          weight: 800
  



