name: pruebas
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^0.1.2
  flutter_webview_plugin: ^0.3.11
  http: ^0.12.0+4
  html: ^0.14.0+3
  provider: ^4.0.5
  flutter_radio: ^0.1.8
  video_player: ^0.10.11+2
  cloud_firestore: ^0.13.7
  flutter_radio_player: 
  firebase_auth: ^0.16.1
  google_sign_in: ^4.5.1
  cached_network_image: ^2.2.0+1
  flutter_custom_clippers: ^1.1.1
  animate_do: ^1.7.2
  flutter_youtube: ^2.0.0
  shared_preferences: ^0.5.8
  font_awesome_flutter: ^8.8.1
  bubble_bottom_bar: ^1.2.0
  
  
  

dev_dependencies:
  flutter_test:
    sdk: flutter
    
  flutter_launcher_icons: "^0.7.5"

flutter_icons:
  
  android: true 
  ios: true

flutter:


  uses-material-design: true


  assets:
    - assets/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-ExtraBold.ttf
          weight: 800
  



